name: Update Stocks Data

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Update stocks data
        env:
          # Store the SQLite Cloud connection URL as a GitHub secret
          SQLITECLOUD_URL: ${{ secrets.SQLITECLOUD_URL }}
        run: |
          echo "Starting incremental update of remote database..."
          # Run the update script which will update the remote database without local commits
          python update_stats.py
          echo "Database update completed successfully!"
